### ISSUE TITLE
Create or Provide a UI front end

### ISSUE THREAD

**Issue by jlogelin** [application-research/lighthouse#3]
Currently there is no user interface for Lighthouse. Since it follows the [registry v2 spec](https://docs.docker.com/registry/spec/api/), a bootstrap might be to use/brand an existing [registry UI](https://github.com/search?q=docker+registry+interface).

**Comment by jlogelin** [comment]
cc @corinne-antonia

**Comment by jlogelin** [comment]
Here's a demo of one of the more popular v2 registry UIs

docker-compose.yml
```
version: "2"
services:
  app:
    image: jc21/registry-ui:latest
    ports:
      - 4000:80
    environment:
      - REGISTRY_HOST=ipcr.io
      - REGISTRY_SSL=false
      - REGISTRY_DOMAIN=ipcr.io
      - REGISTRY_STORAGE_DELETE_ENABLED=
    restart: on-failure
```

`docker-compose up`
